import type { BlogPostEntry } from "../blogMeta";
import blogAriseJohnsonCraft from "@/assets/blog-arise-johnson-craft-models.jpg";

const post: BlogPostEntry = {
  title: "ARISE, Johnson, or CRAFT? How to Choose the Right Intervention Model for Your Family",
  author: "Matt Brown",
  date: "2026-04-08",
  image: blogAriseJohnsonCraft,
  imageAlt: "A professional interventionist discussing intervention model options with a family in a warm living room",
  content: [
    "If you've been searching for a professional interventionist, you've probably come across terms like the Johnson Model, ARISE, or CRAFT — and wondered what any of it means. More importantly, you may be wondering which intervention model is right for your family and your loved one.",
    "The short answer: different intervention models work differently, and the right choice depends on your family's situation, your loved one's personality, and the severity of the addiction. Understanding the differences between these approaches isn't just academic — it directly affects how you prepare, what you say, and whether your loved one agrees to accept help.",
    "This guide breaks down the three most commonly used intervention models, explains what each one looks like in practice, and helps you have an informed conversation with the professional interventionist you hire.",
    "## What Is an Intervention Model — and Why Does It Matter?",
    "An intervention model is a structured method for helping a person in active addiction recognize their situation and agree to seek treatment. Each model has a different philosophy about how to approach the addicted person, how much the family is involved, and what happens when the person resists.",
    "The model your interventionist uses shapes the entire experience — from how the family prepares, to how the conversation unfolds, to how the interventionist responds if your loved one gets angry or shuts down. That's why it matters to ask the professionals you're considering which model they use and why they recommend it for your specific situation.",
    "The three most widely used models in the United States are the Johnson Intervention Model, the ARISE Model, and CRAFT (Community Reinforcement and Family Training). Here's what each one actually looks like.",
    "## The Johnson Intervention Model: Structured, Direct, and Well-Known",
    "The Johnson Model is the most widely recognized intervention approach and what most people picture when they think of a \"traditional\" intervention. Developed by Vernon Johnson in the 1960s, it involves a surprise meeting where family members, friends, and the interventionist confront the addicted person with specific examples of how their behavior has caused harm.",
    "### What a Johnson Intervention Looks Like",
    "The family gathers in secret beforehand — sometimes for several days — to prepare with the interventionist. Each participant writes and reads a personal letter describing specific incidents, the emotional impact, and what they are willing to do if the person refuses help. A treatment placement is arranged in advance, and transportation is often ready to go the same day.",
    "### When the Johnson Model Works Best",
    "This model tends to work well when:\n• The person is in denial and has consistently refused earlier conversations about help\n• The addiction has reached a crisis level and waiting longer carries serious risk\n• The family is unified, motivated, and able to hold firm on consequences\n• A specific consequence — such as legal action, loss of housing, or relationship boundaries — is meaningful enough to influence the person's decision",
    "The Johnson Model requires a high level of family commitment and emotional readiness. The surprise element can initially create resistance, but when executed well by an experienced professional, the structure itself provides clarity that helps many people say yes.",
    "## The ARISE Model: Invitational, Collaborative, and Ongoing",
    "The ARISE Model takes a fundamentally different approach. Rather than confronting the addicted person by surprise, ARISE invites them to be part of the process from the beginning. Developed by Judith Landau and James Garrett, ARISE stands for A Relational Intervention Sequence for Engagement.",
    "### What an ARISE Intervention Looks Like",
    "The process starts with a phone call between a family member and the interventionist. From there, it moves through a sequence of steps — often beginning with the family gathering without the addicted person, then progressing to an open invitation for the person to join future meetings. The goal is engagement over confrontation.",
    "ARISE builds what is called a \"caring community\" around the person — a network of people who love them and are committed to their recovery, regardless of whether the person agrees to treatment on day one. This can unfold over days or weeks.",
    "### When the ARISE Model Works Best",
    "ARISE tends to work well when:\n• The addicted person has some awareness of their problem and might be open to dialogue\n• The family wants a gentler, less confrontational approach\n• Relationship preservation is a primary concern\n• There is time — the situation, while serious, is not an immediate life-or-death emergency",
    "ARISE research shows that the vast majority of people who participate in the ARISE process eventually agree to treatment — often without ever needing to reach a formal intervention meeting. The invitational model reduces shame, which for many people is the biggest barrier to seeking help.",
    "## CRAFT: A Family Skills Approach — With or Without a Formal Intervention",
    "CRAFT — Community Reinforcement and Family Training — is a research-backed approach that focuses on teaching family members specific skills to change the dynamics that keep addiction going. Developed by Robert Meyers, CRAFT is often used independently of a formal one-time intervention.",
    "### What CRAFT Looks Like in Practice",
    "Rather than planning a single meeting, CRAFT trains family members over several sessions to recognize patterns of enabling, to reinforce non-using behavior, to allow natural consequences to occur, and to communicate with the addicted person in ways that make treatment more attractive. Family members learn to take care of themselves while strategically shifting the environment around their loved one.",
    "### When CRAFT Is the Right Fit",
    "CRAFT works well when:\n• The family is willing to invest time in learning new skills and approaches\n• Previous intervention attempts have been unsuccessful\n• The family wants tools to improve their own wellbeing regardless of whether the loved one seeks treatment\n• The person shows some ambivalence — they're not entirely resistant but haven't committed to getting help",
    "CRAFT has a strong evidence base. Studies show that families who use CRAFT are significantly more likely to get their loved one into treatment than those who use Al-Anon alone or traditional confrontational interventions. It also consistently improves the mental health and quality of life of the family members themselves.",
    "## How to Choose the Right Intervention Model for Your Family",
    "There is no single \"best\" intervention model. The right choice depends on several factors — and a qualified professional interventionist will assess your situation carefully before recommending an approach. Here are the questions to think through:\n• How severe is the addiction? If your loved one is in immediate physical danger, the urgency may point toward a more structured, time-limited approach.\n• How resistant is your loved one? Someone who has firmly and repeatedly refused help may need a different approach than someone who is ambivalent or occasionally open to conversation.\n• What is the family's capacity? Are the people involved emotionally prepared to hold firm on consequences, or do they need tools to change their own patterns first?\n• What is the relationship history? If there is significant trauma or a history of explosive conflict, a less confrontational model may protect both the relationship and the process.",
    "A trained interventionist will ask you all of these questions and more. Their job is not to impose a model but to recommend the approach most likely to result in your loved one saying yes to treatment — while doing the least harm to your family in the process.",
    "## The Standard That Matters Most: Professional Training and Ethical Practice",
    "Whatever model a professional uses, what matters most is that they are properly trained, ethically grounded, and honest about both the strengths and limitations of their approach. The intervention field is not regulated the same way in every state, which means the responsibility falls on families to ask the right questions.",
    "Ask any interventionist you're considering: Which model do you use? Why? Have you been formally trained in it? What happens if my loved one refuses? A professional with real training and real experience will answer those questions clearly and without defensiveness.",
    "At TheInterventionistNetwork.com, every professional in our directory meets a standard of training, experience, and ethical practice. Whether the right model for your family is Johnson, ARISE, CRAFT, or a combination approach, we can help connect you with someone qualified to make that call.",
    "## Frequently Asked Questions",
    "## What is the most effective intervention model?",
    "Research supports multiple models depending on the situation. CRAFT has the strongest published evidence base for getting a loved one into treatment and improving family wellbeing. The Johnson Model remains widely used for acute crisis situations. The ARISE Model shows strong success rates with an invitational approach. The best model depends on your loved one, your family, and the severity of the addiction.",
    "## What is the difference between ARISE and the Johnson Model?",
    "The Johnson Model uses a surprise confrontation where the addicted person is not told the meeting is happening in advance. The ARISE Model invites the person to participate from the beginning, using a relational approach built around community support rather than surprise. Johnson is typically more time-limited; ARISE can unfold over days or weeks.",
    "## Can a professional interventionist use more than one model?",
    "Yes. Many experienced interventionists are trained in multiple models and adapt their approach based on the family's situation. Rather than rigidly following one model, a skilled professional assesses each case and draws on different techniques as needed. This flexibility is a sign of experience, not inconsistency.",
    "## Is CRAFT the same as an intervention?",
    "Not exactly. CRAFT is a family skills training approach that can lead to treatment entry without a formal intervention meeting. It teaches family members how to change the environment and their interactions in ways that make getting help more likely. Some interventionists incorporate CRAFT principles into a broader intervention plan.",
    "## What should I ask an interventionist about their model?",
    "Ask which model or models they are trained in, why they recommend a specific approach for your situation, and what happens if your loved one refuses treatment. A qualified professional should be able to explain their reasoning clearly. Also ask about their training credentials and how many interventions they have facilitated.",
    "## How do I find an interventionist trained in these models?",
    "TheInterventionistNetwork.com maintains a directory of professional interventionists who meet verified standards of training and experience. You can search by location and connect directly with a professional who can assess your situation and recommend the right approach for your family.",
  ],
};

export default post;
