import type { BlogPostEntry } from "../blogMeta";
import blogConfidentialityInterventionPractice from "@/assets/blog-confidentiality-intervention-practice.jpg";

const post: BlogPostEntry = {
  title: "Confidentiality and Information Sharing in Intervention Practice: Where the Lines Actually Are",
  author: "Matt Brown",
  date: "2026-06-11",
  image: blogConfidentialityInterventionPractice,
  imageAlt: "Closed manila folder, fountain pen, and consent form on a warmly lit desk symbolizing confidentiality in intervention practice",
  content: [
    "Confidentiality in intervention practice is more complicated than it looks from the outside. Unlike a therapist with a single client, an interventionist works inside a family system — multiple people, multiple agendas, and one identified patient who may not have signed anything. Knowing what you can share, with whom, and when is the foundation of trust that makes this work possible.",
    "Most interventionists learn this the hard way: a well-meaning update to a worried parent, a forwarded email, a casual mention to a treatment center — and suddenly you're explaining to a client why their information moved without their knowledge. The damage isn't always legal. Often it's relational, and it's permanent.",
    "This article lays out the practical framework — not a substitute for legal counsel, but a working map for the gray areas that come up constantly: HIPAA's actual reach, family communication, treatment center coordination, and documentation that protects everyone, including you.",
    "## Does HIPAA Apply to Interventionists?",
    "HIPAA applies directly to 'covered entities' — health plans, healthcare clearinghouses, and providers who transmit health information electronically in connection with covered transactions. Most independent interventionists are not covered entities in the strict legal sense. But that fact is far less protective than it sounds, and treating it as a loophole is a mistake.",
    "First, if you bill insurance, contract with treatment centers, or operate under a clinical license (LADC, LCSW, LPC, etc.), you may be a covered entity or a business associate of one. Second, even when HIPAA doesn't technically apply, 42 CFR Part 2 — the federal law governing substance use disorder treatment records — has its own, often stricter, rules, and the treatment centers you work with are bound by it.",
    "Most importantly: clients don't care about legal technicalities. They care whether you keep your word about what stays private. The professional standard you should hold yourself to is the same regardless of your covered-entity status — informed consent before information moves, full stop.",
    "## Who Is Your Client, and Who Gets Information?",
    "This is the question that causes the most confusion, because the honest answer is: it depends on how you've structured the engagement, and you need to decide before the work begins — not mid-crisis.",
    "In most interventions, the family is paying and the identified patient is the subject of the work. That's legitimate and common. But it doesn't mean the identified patient has no confidentiality interest, especially once they've engaged with you directly or entered treatment.",
    "### Before the Intervention",
    "During planning, your primary working relationship is with the family members who hired you, and information flows relatively freely among that group. Be explicit at the outset about what 'the family' means — is it the whole sibling group, or just the parents who are paying? Adult children, ex-spouses, and extended family often assume access they haven't been granted.",
    "### After the Intervention",
    "Once the identified patient agrees to treatment, the dynamic shifts. They're now a person receiving care, often from a facility bound by 42 CFR Part 2. From this point forward, any sharing of their treatment information — even which facility they're at — should go through a signed release, not the assumption that 'the family already knows everything.'",
    "This is the moment many interventionists get into trouble. A parent calls asking how their adult child is doing in treatment three weeks in, and the interventionist — wanting to be helpful — shares an update without a release on file. That's a problem for the treatment center, for the interventionist, and for the trust the client placed in the process.",
    "## How Should Interventionists Handle Releases of Information?",
    "Releases of information should be built into intake, not treated as an afterthought. A clear, written release — naming who can receive what, for what purpose, and for how long — protects the client, the family, and you.",
    "Get it in writing before the intervention, when possible. If the identified patient is willing to sign a release authorizing communication between you, the family, and the treatment center as part of agreeing to go, do it then — while the purpose is clear to everyone.",
    "Specify scope, not blanket access. 'Share progress updates and discharge planning with [parent names]' is different from 'share everything with my family.' Specificity protects the relationship long after the crisis passes.",
    "Set an expiration or review point. A release signed in week one of treatment may not reflect what the client wants shared by week eight, especially once they're doing their own work in family therapy.",
    "## What About Information You Learn Informally?",
    "Some of the most sensitive information doesn't arrive through formal channels. A sibling tells you something 'off the record' during a prep call. A spouse mentions a detail about finances or an affair that has nothing to do with the substance use but everything to do with the family's willingness to participate.",
    "None of this is covered by a release form, and it requires judgment. The operating principle: information shared in confidence stays with you unless there's a safety reason to disclose it, or the person who shared it gives permission. This matters most with information that could be used as leverage — a family member hoping you'll 'work a secret into' the intervention is asking you to do something that will backfire, and you should decline.",
    "## Coordinating With Treatment Centers Without Overstepping",
    "Strong referral relationships with treatment centers are one of the most valuable assets an interventionist can build — and they depend on getting information sharing right. Admissions teams need enough information to do a proper clinical assessment. They don't need, and shouldn't receive, everything you know about the family.",
    "A useful filter: share what's clinically relevant — substance use history, co-occurring concerns, safety issues, prior treatment episodes, family dynamics that will affect treatment planning. Hold back what's only relevant to the intervention itself — family conflict details, financial disputes, or personal disclosures that don't bear on care. When in doubt, ask the family and the client what they're comfortable having you share, and document that conversation.",
    "## Building Confidentiality Into Your Practice From the Start",
    "The interventionists who navigate this well aren't the ones who memorize statute numbers. They're the ones who set expectations clearly at intake, document consistently, and treat every piece of information as belonging to the person it's about — not to whoever is asking for it.",
    "Address confidentiality explicitly in your first conversation with the family, before any details are shared. Use written releases for information sharing involving the identified patient once they're in treatment. Keep your case files organized, access-limited, and separate from informal notes. When someone shares something 'off the record,' treat it that way — and say so if you're not sure you can.",
    "None of this slows the work down when it's built in from the beginning. What it does is protect the trust that makes intervention work possible — trust from families taking an enormous risk by inviting you into their crisis, and from the identified patient, who deserves to know their privacy will be respected once they're in care.",
    "## Frequently Asked Questions",
    "### Do independent interventionists have to follow HIPAA?",
    "Most independent interventionists aren't HIPAA-covered entities unless they bill insurance, hold a clinical license, or act as a business associate of one. But 42 CFR Part 2 governs substance use records held by treatment programs, and best practice is to treat client information with the same care regardless of which law applies.",
    "### Can I update a family member on how their loved one is doing in treatment?",
    "Only with a signed release from the client specifying what can be shared and with whom. Without it, even basic updates can violate confidentiality and damage the treatment center relationship.",
    "### What if a family member asks me to keep a secret from the rest of the family?",
    "Information shared in confidence should generally stay confidential unless there's a safety concern. Be cautious about holding information that could be used as leverage during the intervention, and be clear that your role is to facilitate direct communication, not manage secrets.",
    "### How much information should I share with a treatment center during admission?",
    "Share what's clinically relevant — substance use history, safety concerns, co-occurring issues, and family dynamics that affect care. Hold back details that don't bear on clinical decisions, and check with the family and client when unsure.",
    "Confidentiality practices are one of the clearest signals of professionalism in this field. Visit TheInterventionistNetwork.com for more resources on building an ethical, sustainable intervention practice.",
  ],
};

export default post;
