import type { BlogPostEntry } from "../blogMeta";
import blogJustFoundOut from "@/assets/blog-just-found-out-loved-one-addiction.jpg";

const post: BlogPostEntry = {
  title: "What to Do When You Find Out a Loved One Is Addicted: First Steps for Families",
  author: "Matt Brown",
  date: "2026-08-12",
  image: blogJustFoundOut,
  imageAlt: "A quiet kitchen table in early morning light with a cold cup of coffee, a notebook, and an empty chair",
  content: [
    "You found the bottles. You saw the texts. Maybe someone finally told you what everyone else already suspected. However it happened, you now know: someone you love is struggling with addiction. And you are sitting with a question that feels enormous — what do I do now?",
    "Here is the short answer to what to do when you find out a loved one is addicted: slow down, get accurate information, avoid confrontation in the heat of the moment, and talk to a professional before you make any big moves. The discovery moment feels like an emergency, but in most cases the real emergency is weeks or months old. You have time to respond well instead of reacting fast.",
    "This guide walks you through the first steps — what helps, what backfires, and when it is time to bring in a professional interventionist.",
    "## What Should You Do in the First 48 Hours?",
    "In the first 48 hours after discovering a loved one's addiction, your job is to stabilize yourself — not to fix them. Do not stage a confrontation, issue ultimatums, or search their room while they sleep. Get grounded, get informed, and get one trusted person in your corner.",
    "That advice frustrates people, and understandably so. Discovery creates a surge of fear and urgency, and urgency wants action. But the actions families take in the first 48 hours — angry confrontations, snap ultimatums, secret searches — are the ones they most often regret. They alert your loved one that they are being watched, deepen the secrecy, and burn trust you will need later.",
    "Instead, focus on three things:",
    "• Write down what you actually know. Facts, dates, what you saw or heard — not interpretations. This record becomes valuable if you later work with a professional.\n• Tell one steady person. Not the whole family group chat. One person who can keep a confidence and stay calm.\n• Rule out immediate danger. If there are signs of overdose risk, suicidal statements, or violence, that changes everything — call 911 or a crisis line now. Everything else in this article assumes safety first.",
    "## Why Shouldn't You Confront Them Right Away?",
    "Immediate confrontation usually fails because addiction is defended by denial, and denial gets stronger under attack. When you confront a loved one in anger, they hear an accusation, not an invitation — and the conversation becomes about your tone instead of their drinking or drug use.",
    "Most families have already run this experiment. The angry kitchen confrontation produces one of three results: denial, a fight, or a promise that does not hold. None of them produce treatment.",
    "That does not mean silence. It means the first real conversation should be planned, calm, and specific. Choose a sober moment. Lead with care, not evidence: \"I love you, and I'm worried about what I'm seeing.\" Name one or two concrete observations without labels or diagnoses. Then listen. You are not trying to win — you are trying to open a door you can walk through again later.",
    "If that conversation goes nowhere, you have lost nothing. You have marked the concern, kept the relationship intact, and gathered information about how deep the denial runs — which is exactly what a professional will want to know.",
    "## What Do Families Get Wrong After Discovering Addiction?",
    "The most common mistakes after discovering a loved one's addiction are secrecy, over-functioning, and going it alone too long. Families rarely fail because they do not care. They fail because they care intensely and channel it into strategies that accidentally protect the addiction.",
    "Watch for these patterns in yourself and your family:",
    "• Covering and cushioning. Calling in sick for them, paying the overdraft, explaining away the missed holiday. Every rescue removes a consequence that might have created motivation to change.\n• Monitoring instead of acting. Counting pills, checking location apps, smelling breath. Surveillance feels like doing something, but it produces anxiety for you and better hiding from them.\n• Keeping it inside the walls. Shame tells families to handle this privately. Isolation is where addiction thrives — and where families burn out.\n• Waiting for rock bottom. The idea that people must lose everything before they can accept help is a myth, and a dangerous one with today's drug supply. Families do not have to wait, and often cannot afford to.",
    "If you recognize yourself in this list, that is not an indictment. It is information. These patterns are nearly universal, and naming them is the first step out of them.",
    "## When Is It Time to Call a Professional Interventionist?",
    "It is time to call a professional interventionist when your direct, caring attempts to raise the concern have been refused or minimized, and the substance use is continuing or escalating. You do not need to wait for an arrest, an overdose, or a lost job. A pattern of denial plus real consequences is enough.",
    "A professional interventionist does far more than orchestrate a single dramatic meeting. A qualified professional will assess the whole situation — the substance use, the family dynamics, any mental health concerns — and design an approach that fits. Sometimes that is a structured family intervention. Sometimes it is coaching the family first, because when the family changes, the person struggling often starts moving too.",
    "Early consultation costs you nothing but an hour. Most reputable interventionists offer an initial conversation that helps you understand your options, whether or not you hire anyone. Families consistently say the same thing afterward: \"I wish we had called sooner.\"",
    "## What Should You Look for in an Interventionist?",
    "Look for credentials such as the CIP (Certified Intervention Professional), verifiable training in a recognized intervention model, professional references, and a clear written agreement covering fees and scope. Be cautious with anyone who guarantees outcomes, pressures you to commit tonight, or is vague about what happens after the intervention. A directory of vetted professionals is a strong starting point.",
    "## How Do You Take Care of Yourself Through This?",
    "You take care of yourself by treating your own support as part of the strategy, not a luxury. Families in this situation routinely develop their own symptoms — sleeplessness, anxiety, obsessive monitoring — and an exhausted family cannot hold a steady position when it matters most.",
    "Concretely: keep your routines, especially sleep and meals. Get connected to family-focused support, whether that is Al-Anon, a family coach, or a therapist who understands addiction.",
    "And release the belief that you caused this or that you can single-handedly cure it. You did not, and you cannot. What you can do is change the environment around the addiction — and that is far more powerful than most families realize.",
    "## The Bottom Line",
    "Discovering a loved one's addiction is disorienting, but your next steps are clearer than they feel right now: stay calm, get the facts, have one planned and caring conversation, refuse the rescue patterns that protect the problem, and bring in professional help early rather than late. Addiction is progressive — but so is a family that gets organized. Working with a credentialed professional who meets real standards of training and ethics gives your family the best chance of turning this discovery into a turning point.",
    "## Frequently Asked Questions",
    "What is the first thing to do when you find out a family member is using drugs? Pause before acting. Confirm there is no immediate safety risk, write down what you actually observed, and confide in one trusted person. Avoid confrontation in the first emotional surge — planned conversations succeed far more often than spontaneous ones.",
    "Should I confront my loved one about their addiction? Yes, but not in anger and not immediately. Plan a calm, sober-moment conversation that leads with concern and names specific observations. If they deny or deflect, do not escalate — that response is information a professional can work with.",
    "How do I know if it's addiction or just a phase? Look at consequences and control. If the use continues despite real costs — health, work, relationships, money — and attempts to cut back keep failing, you are likely looking at addiction rather than a phase. A professional assessment can tell you for certain.",
    "When should a family call a professional interventionist? Call when caring, direct attempts to address the problem have been refused and the use is continuing or escalating. You do not need a catastrophe first. Most interventionists offer an initial consultation that helps you understand your options at no obligation.",
    "Can a family force someone into treatment? In most U.S. states, adults cannot be forced into treatment outside narrow legal circumstances. But families are not powerless — a professionally guided intervention changes the choice the person faces, and the majority of well-planned interventions result in the person accepting help.",
    "How much does hiring an interventionist cost? Professional intervention services typically range from $2,500 to $10,000 or more depending on scope, travel, and case complexity. Reputable professionals put fees and scope in writing before you commit. Treatment costs are separate and often carry insurance coverage.",
    "## Find the Right Help",
    "You do not have to figure this out alone, and you do not have to get it perfect. Browse vetted professional interventionists in the directory, learn what qualified help looks like, and take the next right step for your family.",
  ],
};

export default post;
