import type { BlogPostEntry } from "../blogMeta";
import blogSettingFeesIntervention from "@/assets/blog-setting-fees-intervention-pricing.jpg";

const post: BlogPostEntry = {
  title: "Setting Fees and Talking Money: A Practitioner's Guide to Pricing Intervention Services",
  author: "Matt Brown",
  date: "2026-06-14",
  image: blogSettingFeesIntervention,
  imageAlt: "Wooden desk with open notebook, pen, calculator, eyeglasses, and coffee, evoking thoughtful pricing for an intervention practice",
  content: [
    "Most interventionists got into this work because of recovery, not spreadsheets. That's a strength when you're in the room with a family. It becomes a liability the moment the conversation turns to intervention services pricing and you find yourself stumbling, discounting, or avoiding the topic entirely. This article is for the colleague who's good at the work and uncomfortable with the invoice.",
    "If you've ever quoted a fee and immediately wanted to apologize for it, or found yourself doing an hour of free 'consultation' that quietly became case management, this is for you. Clear pricing isn't about extracting more money from families in crisis. It's about building a practice that can sustain the work you're called to do — for this family and the next one.",
    "## Why Does Intervention Pricing Vary So Much Between Practitioners?",
    "Intervention pricing varies because the service itself varies widely in scope, time investment, and what's bundled in. A flat fee from one interventionist might cover only the day of the intervention, while another's identical-sounding fee includes weeks of pre-engagement work, travel, and 90 days of aftercare coordination.",
    "Families researching cost will often compare numbers without understanding what's underneath them. That's not their fault — it's an industry-wide transparency problem. The fix isn't to match competitors' numbers. It's to know your own numbers cold: hours of pre-call work, travel days, case management hours, and aftercare touchpoints, all priced honestly.",
    "A useful exercise: track your actual hours on your next three cases, from first call to 30-day follow-up. Most practitioners are surprised by how much unpaid time is baked into a single case. That number is your real starting point for a sustainable fee.",
    "## What Should Be Included in an Intervention Fee?",
    "An intervention fee should reflect every phase of the work, not just the day of the intervention itself. At minimum, that means pre-engagement assessment calls, family preparation sessions, the intervention day, treatment placement coordination, and a defined period of follow-up.",
    "Consider structuring your fee around these phases:",
    "- **Pre-engagement:** assessment calls, family system mapping, readiness evaluation.",
    "- **Preparation:** education sessions, letter-writing support, rehearsal.",
    "- **Intervention day:** travel, the session itself, immediate placement logistics.",
    "- **Transition:** handoff to treatment, family debrief.",
    "- **Follow-up:** a defined window of check-ins (commonly 30 or 90 days).",
    "Naming each phase — even briefly — does two things. It helps the family understand what they're paying for, and it protects you from scope creep when a 'quick question' three weeks post-placement turns into another full coaching relationship.",
    "## How Do You Talk About Fees Without Feeling Like a Salesperson?",
    "You talk about fees the same way you talk about everything else in this work: directly, calmly, and without over-explaining. Families in crisis can tolerate a clear number delivered with confidence far better than a nervous one delivered with a dozen caveats.",
    "A simple structure works well: state what the service includes, state the fee, then stop talking. \"This covers everything from today's call through 30 days after placement. The fee is [amount].\" Resist the urge to immediately soften it with \"but we can work something out\" before the family has even responded.",
    "If a family pushes back on cost, that's information — sometimes about their finances, sometimes about their ambivalence toward the whole process. Either way, it's worth a direct response: \"I hear that this is a real number. Let's talk about what's true right now about your budget, and what options exist.\" That's different from immediately discounting out of discomfort.",
    "It also helps to remember: the fee conversation is happening regardless of how you feel about it. The only choice is whether you have it on purpose, with a number you've thought through, or reactively, in the moment, shaped by whatever anxiety shows up that day.",
    "## Should You Offer Sliding Scale or Payment Plans?",
    "Sliding scale and payment plans can work, but they need structure or they quietly erode your practice. Without clear criteria, 'sliding scale' tends to become 'whatever this particular family's urgency makes me feel okay charging' — which isn't a policy, it's a mood.",
    "If you offer a reduced rate, define the criteria in advance: a documented income threshold, a limited number of reduced-fee slots per quarter, or a partnership with a nonprofit that subsidizes part of the cost. This protects both the family (consistent, fair treatment) and you (a policy you can point to instead of negotiating from scratch every time).",
    "Payment plans are reasonable for a service this significant. What matters is putting them in writing — amounts, dates, and what happens if a payment is missed — before the work begins, not after a difficult moment makes the conversation harder than it needs to be.",
    "## How Does Pricing Connect to the Business Side of an Intervention Practice?",
    "Pricing is one of the clearest signals of whether a practice is built to last or built to survive month to month. Underpricing doesn't just affect your income — it affects your capacity, your follow-through, and eventually your presence with the families who need you most.",
    "A practitioner who is quietly resentful about an underpriced case is not bringing their full self to that case. Families can feel that, even if they can't name it. Pricing your work honestly is part of showing up fully — it's not separate from the clinical work, it supports it.",
    "This is also where referral relationships matter. A treatment center that understands your fee structure and what it includes can set accurate expectations with families before they ever call you. That conversation — proactively educating your referral partners on your scope and pricing — is worth having on its own, separate from any individual case.",
    "## The Bottom Line",
    "Talking about money is not separate from the clinical relationship — it's part of it. A practitioner who can state a fee clearly, hold a boundary on scope, and structure payment fairly is modeling exactly the kind of clear, values-driven communication that families in crisis are often missing. The work deserves to be priced like the serious clinical service it is.",
    "If you're building or refining your practice and want to connect with other professionals navigating these same questions, visit TheInterventionistNetwork.com.",
    "## Frequently Asked Questions",
    "### How much does a professional intervention typically cost?",
    "Fees vary widely depending on scope, travel, and what's included, but most professional interventions range from a few thousand dollars to well into five figures when travel, multi-day preparation, and extended follow-up are included. The number matters less than understanding exactly what phases of work it covers.",
    "### What's typically included in an intervention fee?",
    "A well-structured fee usually covers pre-engagement assessment, family preparation, the intervention day itself, placement coordination, and a defined follow-up period — commonly 30 to 90 days. Travel costs may be included or billed separately.",
    "### Is it normal for interventionists to offer payment plans?",
    "Yes, payment plans are common given the significant cost of intervention services. The key is putting the plan in writing before work begins, including amounts, due dates, and what happens if a payment is missed.",
    "### How do I know if I'm underpricing my services?",
    "A useful check is tracking your actual hours across several cases — including pre-call work, travel, and follow-up — and comparing that to your fee. If the resulting hourly rate is far below what you'd consider sustainable, your fee likely doesn't reflect the real scope of the work.",
    "### Should fees be negotiable based on a family's financial situation?",
    "A defined sliding scale or limited number of reduced-fee slots, set up in advance with clear criteria, is more sustainable than case-by-case negotiation. Ad hoc discounting tends to create inconsistency and can quietly undermine the practice over time.",
    "### How can referral partners help with pricing transparency?",
    "Treatment centers and other referral partners who understand an interventionist's fee structure can set accurate expectations with families before the first call, reducing friction and helping families come into the conversation already informed.",
  ],
};

export default post;
