import type { BlogPostEntry } from "../blogMeta";
import blogWhoIsTheClient from "@/assets/blog-who-is-the-client-contracting.jpg";

const post: BlogPostEntry = {
  title: "Who Is the Client? Role Clarity and Contracting in Professional Intervention Work",
  author: "Matt Brown",
  date: "2026-08-11",
  image: blogWhoIsTheClient,
  imageAlt: "A signed professional agreement and pen on a wooden table in a quiet home, soft window light",
  content: [
    "Ask ten interventionists who is the client in intervention work and you will get at least three different answers: the family who hired you, the loved one who needs treatment, or the family system as a whole. That ambiguity is not academic. It shapes what you promise, what you disclose, whose interests you protect when they conflict, and what you do when the person paying your fee asks for something the engagement should not deliver.",
    "Most of the messy moments in this work — the mid-engagement blowups, the boundary crossings, the ethical gray zones — trace back to a contracting conversation that never happened or happened too vaguely. This article walks through how to define the client relationship clearly, what a solid intervention contract covers, and how to hold role clarity when the family system starts pulling on it.",
    "## Why Does Role Clarity Matter So Much in Intervention Work?",
    "Role clarity matters because intervention work sits at the intersection of several relationships that ordinary clinical work keeps separate. The person who hires you is rarely the person whose behavior is the focus. The people in the room have competing interests, long histories, and different levels of commitment to change. Without a clearly defined role, you become whatever each family member needs you to be — and those needs contradict each other.",
    "Consider the common pulls. The mother who hired you wants an advocate. The skeptical sibling wants a neutral referee. The father paying the invoice wants a guaranteed outcome.",
    "Each expectation is reasonable from that person's seat, and you cannot fulfill them all. Role clarity means deciding, before the pressure arrives, what you are for — so you answer from a defined professional position rather than improvising under emotional load.",
    "## Who Is the Client in Intervention Work — the Family, the Loved One, or the System?",
    "The most defensible answer for most engagements is this: the family system is the client, the engagement goal is defined in the contract, and the identified loved one's welfare is a duty you carry regardless of who pays. You serve the system's stated goal — usually moving a loved one toward appropriate treatment and helping the family change the patterns that sustain the crisis — not any single member's agenda.",
    "This framing solves several practical problems. It explains why you will not report back privately to the hiring party about everything another family member said in preparation sessions. It explains why you keep working on family patterns even if the loved one refuses treatment. And it explains why you will decline instructions that serve one member's interests at the expense of the system's health — for example, being asked to engineer an outcome in a custody dispute under the banner of an intervention.",
    "Whatever position you take, take it explicitly. Say it in the first call, put it in the agreement, and repeat it when the system tests it. A client definition that lives only in your head protects no one.",
    "## What Should an Intervention Contract Actually Cover?",
    "A working intervention contract covers scope, roles, confidentiality, fees, and endings — in plain language the family can actually absorb during a crisis. It is both a legal instrument and a clinical tool: the act of walking a family through it is often your first structured teaching moment about boundaries. At minimum, address these elements:",
    "• Scope and goal: what the engagement includes (assessment, preparation sessions, intervention day, case management window) and what it does not (therapy, legal advocacy, guaranteed admission or sobriety).\n• Client definition: who you serve, who receives communication, and who has decision-making authority when family members disagree.\n• Confidentiality terms: what you will and will not share among family members, and your duty-to-act exceptions for safety concerns.\n• Fees and travel: what is included, what triggers additional charges, and your policy if the intervention is postponed or the loved one refuses.\n• Ending conditions: how the engagement concludes, what follow-up is included, and the circumstances under which you would withdraw.",
    "The withdrawal clause deserves emphasis. Naming upfront that you may step away — if safety deteriorates, if the family works against the agreed plan, or if you are asked to act outside your scope — makes a later withdrawal a contract term being exercised rather than an abandonment.",
    "## How Do You Manage Competing Agendas Inside the Family?",
    "You manage competing agendas by surfacing them early, naming them without judgment, and returning every dispute to the contracted goal. Hidden agendas do the most damage when they stay hidden; your preparation sessions are where you bring them into the light while there is still time to work with them.",
    "In practice, that means asking each participant privately what outcome they actually want — not what they are supposed to want. One member wants treatment; another wants an apology; another wants permission to cut contact; another quietly wants the intervention to fail so the family narrative stays intact. None of these makes someone a bad actor. They make the system a system.",
    "When agendas collide mid-engagement, the contract is your anchor. \"We agreed the goal of this engagement is getting your brother to treatment and changing the patterns around him. What you're asking me for is different from that. Let's look at the difference.\" Said calmly, this reframes conflict as a scope question rather than a loyalty test — and keeps you out of the triangle the system is trying to build around you.",
    "## What Does Role Confusion Look Like Mid-Engagement?",
    "Role confusion rarely announces itself. It shows up as small requests that feel harmless in the moment: a private phone call one member wants kept from the others, a request to \"just talk to\" an estranged relative, pressure to extend your involvement into marital conflict or parenting disputes, or the hiring party treating you as their personal coach between sessions.",
    "Each of these deserves a pause rather than a reflex. The test question is simple: does saying yes serve the contracted goal, or one person's position within the system? If it is the latter, the honest response is a referral, a redirect, or a respectful no — tied back to the agreement they signed.",
    "Interventionists in recovery face an added pull here: our instinct to help is well developed, and families in pain are skilled at recruiting it. Role clarity is not a limit on compassion — it is what makes compassion sustainable across a full career.",
    "## The Standard This Sets for the Field",
    "Clear contracting is one of the quiet markers separating professional intervention practice from well-meaning improvisation. Families in crisis deserve to know exactly what they are buying, who the interventionist serves, and where the boundaries sit — before intervention day, not after something goes sideways. Practitioners who hold this standard protect their clients, their outcomes, and the credibility of the field itself.",
    "## Frequently Asked Questions",
    "Who is the client in a professional intervention? In most engagements, the family system is the client, with the engagement goal defined by contract. The interventionist serves the agreed goal — typically moving a loved one toward treatment and shifting the family patterns around the addiction — while carrying an independent duty of care toward the loved one's safety and dignity.",
    "Should the identified loved one sign the intervention contract? No. The engagement agreement is signed by the hiring family members before the loved one is aware of the process. If the loved one enters treatment or ongoing case management, separate consent and agreements are established with them directly at that point.",
    "What happens if family members disagree about the intervention goal? The interventionist surfaces the disagreement during preparation, works toward a unified goal, and documents it in the agreement. If the family cannot align on a basic goal, that is significant clinical information — and sometimes a reason to delay the intervention rather than proceed with a divided team.",
    "Can an interventionist keep secrets for one family member? Generally no. Most practitioners contract for transparency within the intervention team, with narrow exceptions for safety-sensitive disclosures. Agreeing to hold one member's secret against the others places the interventionist inside the family's triangulation patterns and undermines the work.",
    "When should an interventionist withdraw from an engagement? Withdrawal is appropriate when safety cannot be managed, when the family persistently works against the contracted plan, or when the interventionist is being asked to act outside ethical scope — such as serving one member's legal or financial position. A well-drafted contract names these conditions in advance.",
  ],
};

export default post;
